name: sipeed-lichee-rv
version: 22-1
summary: Sipeed Lichee RV gadget
description: |
  Support files for booting Sipeed Lichee RV gadget
type: gadget
base: core22
assumes: [kernel-assets]
architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]

confinement: strict
grade: stable

# Adapted from https://fedoraproject.org/wiki/Architectures/RISC-V/Allwinner

parts:
  boot-scr:
    plugin: nil
    source: sources/
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage \
        -T script \
        -C none \
        -n 'Boot Script' \
        -d boot.scr.in \
        ${CRAFT_PART_INSTALL}/boot.scr

  spl:
    plugin: nil
    source: https://github.com/smaeul/sun20i_d1_spl.git
    source-type: git
    source-branch: mainline
    source-depth: 1
    build-packages:
      - build-essential
      - on amd64:
        - gcc-riscv64-linux-gnu
      - else:
        - gcc
    override-build: |
      make \
        CROSS_COMPILE=riscv64-linux-gnu- \
        p=sun20iw1p1 \
        mmc

      cp -f ${CRAFT_PART_BUILD}/nboot/boot0_sdcard_sun20iw1p1.bin \
        ${CRAFT_PART_INSTALL}/

  opensbi:
    plugin: make
    source: https://github.com/smaeul/opensbi.git
    source-type: git
    source-branch: d1-wip
    source-depth: 1
    override-build: |
      CROSS_COMPILE=riscv64-linux-gnu- \
        PLATFORM=generic \
        FW_OPTIONS=0x2 \
        FW_PIC=y \
        make

  u-boot:
    after: [opensbi]
    plugin: make
    source: https://github.com/smaeul/u-boot.git
    source-type: git
    source-branch: d1-wip
    source-depth: 1
    build-packages:
      - bison
      - build-essential
      - flex
      - libpython3-dev
      - libssl-dev
      - python3-distutils
      - swig
      - on amd64:
        - gcc-riscv64-linux-gnu
      - else:
        - gcc
    override-build: |
      make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- lichee_rv_dock_defconfig

      sed -i 's/CONFIG_DEFAULT_DEVICE_TREE="sun20i-d1-lichee-rv"/CONFIG_DEFAULT_DEVICE_TREE="sun20i-d1-lichee-rv-dock"/' .config
      sed -i 's/# CONFIG_OF_LIBFDT_OVERLAY is not set/CONFIG_OF_LIBFDT_OVERLAY=y/' .config


      make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- all

      cp -f arch/riscv/dts/sun20i-d1-lichee-rv-dock.dtb .
      cp -f ${CRAFT_PART_SRC}/../../opensbi/build/build/platform/generic/firmware/fw_dynamic.bin .

      tools/mkenvimage \
        -r -s 4096 \
        -o ${SNAPCRAFT_PART_INSTALL}/boot.sel - < /dev/null

      tools/mkimage \
        -T sunxi_toc1 \
        -d ${CRAFT_PROJECT_DIR}/sources/toc1.cfg \
        ${CRAFT_PART_INSTALL}/u-boot.toc1

      touch ${CRAFT_PART_INSTALL}/uboot.conf
    prime:
      - u-boot.toc1
      - boot.sel
      - uboot.conf
