name: virt-kernel
adopt-info: kernel
build-base: core22
summary: A RISC-V 64-bit kernel for Qemu's virt board
description: This is a snapped kernel for an emulated RISC-V system.
type: kernel
architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]

grade: stable
confinement: strict

package-repositories:
  - type: apt
    url: https://ppa.launchpadcontent.net/canonical-kernel-team/ppa/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [riscv64]
    key-id: 110E21D8B0E2A1F0243AF6820856F197B892ACEA
    key-server: keyserver.ubuntu.com

parts:
  kernel:
    plugin: nil
    stage-packages: 
      - linux-generic:${CRAFT_TARGET_ARCH}
    override-stage: |
      install -Dm644 ${CRAFT_PROJECT_DIR}/sources/riscv64-virt.dtb \
        ${CRAFT_PART_INSTALL}/dtbs/riscv64-virt.dtb

      craftctl default
      craftctl set version=$(ls ${CRAFT_PART_INSTALL}/modules/ | cut -f1 -d/)
    stage:
      - -boot/
      - -etc/
      - -usr/
    organize:
      boot/vmlinuz-*: Image
      boot/config-*: kconfig
      lib/modules: modules/
      lib/firmware/regulatory.db*: firmware/
      usr/src/linux-headers-*/Module.symvers: Module.symvers
    prime:
      - -Image

  initrd:
    after: [kernel]
    plugin: nil
    build-packages:
      - lz4
      - kmod
    override-build: |
      KVER=5.15.0-1020-generic

      cp -f ${CRAFT_PROJECT_DIR}/sources/uc-initrd_*_riscv64.img ./

      lz4cat uc-initrd_*_riscv64.img | cpio -idm
      rm -f uc-initrd_*_riscv64.img

      install -Dm644 ${CRAFT_STAGE}/modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko \
        lib/modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko
      install -Dm644 ${CRAFT_STAGE}/modules/${KVER}/kernel/fs/fuse/virtiofs.ko \
        lib/modules/${KVER}/kernel/fs/fuse/virtiofs.ko
      install -Dm644 ${CRAFT_STAGE}/modules/${KVER}/kernel/drivers/block/virtio_blk.ko \
        lib/modules/${KVER}/kernel/drivers/block/virtio_blk.ko

      depmod -avb . ${KVER}

      find . | cpio -o -H newc -R 0:0 | lz4 -9 -l > ${CRAFT_PART_INSTALL}/initrd.img
    prime:
      - -initrd.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware/
