name: sipeed-lichee-rv-kernel
summary: A RISC-V 64-bit kernel for Sipeed's Lichee RV board + dock
description: A RISC-V 64-bit kernel for Sipeed's Lichee RV board + dock

grade: stable
build-base: core20
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, riscv64]
    run-on:   [riscv64]

parts:
  kernel:
    plugin: x-kernel
    source: https://github.com/smaeul/linux.git
    source-branch: riscv/d1-wip
    source-depth: 1
    kernel-compiler: riscv64-linux-gnu-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-device-trees:
      - allwinner/sun20i-d1-lichee-rv-dock
    kdefconfig:
      - nezha_defconfig
      - generic.config
      - containers.config
      - security.config
      - snappy.config
      - systemd.config
    override-pull: |
      snapcraftctl pull
      git apply ${SNAPCRAFT_PROJECT_DIR}/patches/configs.patch
      git apply ${SNAPCRAFT_PROJECT_DIR}/patches/apparmor-5.18.patch
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/sources/uc-initrd_20-*_riscv64.snap \
          ${SNAPCRAFT_PART_BUILD}/uc-initrd_20-stable_riscv64.snap

      snapcraftctl build
      snapcraftctl set-version "$(strings vmlinux | grep "Linux version 5"|cut -d ' ' -f 3)"
    prime:
      - -config*
      - -Image-*
      - -initrd.img-*
      - -System.map*


  firmware:
    plugin: dump
    source: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
    source-type: git
    source-branch: main
    source-depth: 1
    organize:
      '*': firmware/

build-packages:
  - bison
  - cpio
  - device-tree-compiler
  - dpkg-dev
  - flex
  - libelf-dev
  - libfdt-dev
  - libssl-dev
  - pkg-config
  - u-boot-tools
  - on amd64:
    - binutils-riscv64-linux-gnu
    - gcc-riscv64-linux-gnu
  - else:
    - gcc
