name: polarfire-kernel
version: 5.15-mchp
summary: A RISC-V 64-bit kernel for the Microchip Polarfire SoC Icecicle
description: |
  A RISC-V 64-bit kernel for the Microchip Polarfire SoC Icecicle
type: kernel
# TODO: evading user-defined plugin issues by choosing a different base
# This should not impact anything related to Ubuntu Core 22;
# the only "user-space" difference is the initrd, and snapd-bootstrap did not
# change between Core20 and Core22.
build-base: core20

architectures:
  - build-on: [amd64, riscv64]
    run-on:   [riscv64]

grade: stable
confinement: strict

parts:
  firmware:
    plugin: dump
    source: https://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc22
    source-type: git
    source-branch: main
    source-depth: 1
    stage-packages:
      - linux-firmware
      - wireless-regdb
    prime:
      - firmware
    organize:
        lib/firmware: firmware

  kernel:
    after: [firmware]
    plugin: x-kernel
    source: https://git.launchpad.net/~dilyn-corner/ubuntu/+source/linux-riscv/+git/jammy
    source-type: git
    source-branch: icicle-fpga
    source-depth: 1
    kernel-compiler: riscv64-linux-gnu-gcc
    kernel-with-firmware: false
    kernel-image-target: Image
    kernel-initrd-channel: stable
    kernel-initrd-compression: gz
    kernel-device-trees:
        - microchip/mpfs-icicle-kit
    kdefconfig: ["snappy_defconfig"]
    kconfigs:
      - CONFIG_SYSTEM_REVOCATION_KEYS=""
      - CONFIG_SYSTEM_TRUSTED_KEYS=""
      - CONFIG_DEFAULT_HOSTNAME="Hermes"
      - CONFIG_DEBUG_INFO_BTF=n
    build-packages:
      - bison
      - cpio
      - device-tree-compiler
      - dpkg-dev
      - dwarves
      - flex
      - libelf-dev
      - libfdt-dev
      - libssl-dev
      - lz4
      - pkg-config
      - u-boot-tools
      - on amd64:
        - binutils-riscv64-linux-gnu
        - gcc-riscv64-linux-gnu
      - else:
        - gcc
    override-build: |
      cp -f ${SNAPCRAFT_PROJECT_DIR}/initrd/uc-initrd_*_riscv64.snap \
        uc-initrd_20-stable_riscv64.snap

      snapcraftctl build
    stage:
      - -config*
      - -canonical-*
      - -Image-*
      - -initrd.img-*
      - -Makefile*
      - -System.map*
    prime:
      - -Image
      - -dtbs
      - -initrd.img
    override-prime: |
      snapcraftctl prime
      ${SNAPCRAFT_STAGE}/trim-firmware ${SNAPCRAFT_PRIME}
    organize:
      kernel.img: Image

  fit-image:
    after: [kernel]
    plugin: dump
    source: fit-image/
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage \
        -f fitImage-riscv64.its \
        ${SNAPCRAFT_PART_INSTALL}/kernel.img
